name: Telegram-bot

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pylint-exit anybadge
    
    - name: Run Tests
      run: |
        python -m pytest tests.py

    - name: Linter
      run: |
        pylint --rcfile=.pylintrc --output-format=text <LIST-OF-FILES-TO-RUN-PYLINT-AGAINST> | tee pylint.txt
        score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
        echo "Pylint score was $score"
        anybadge --value=$score --file=public/pylint.svg pylint
    
    - name: "UploadArtifacts"
      uses: actions/upload-artifact@v2
      with:
        name: Distributive
        path: |
          public/pylint.svg
